### ISSUE TITLE
Feature Request: Adding downloading-screen 

### ISSUE THREAD

**Issue by Grashee** [beat-saber-modding-group/BeatSaberModInstaller#11]
Hi Guys,

This is a feature request!
It would be nice if there is a download screen where the user can see if all the songs have been downloaded.

Best regards,
Robert

**Comment by megalon** [comment]
If you are referring to the IngameDownloader mod, that does have a download screen. 
It is the menu panel to the left of the song select.

Here is the github repo for it, if you still have issues
https://github.com/andruzzzhka/BeatSaverDownloader

This repo is only for the ModManager itself. I plan on adding links to the repos of all of the other available mods within the ModManager soon.
