### ISSUE TITLE
Save selected mods and load on next launch

### ISSUE THREAD

**Issue by megalon** [beat-saber-modding-group/BeatSaberModInstaller#16]
This is essentially the most requested feature of the Mod Manager.

* Save the mods that the user has selected when they click the "Install / Update" button
* Load this save file when the Mod Manager starts up

**Comment by RedDrumJay** [comment]
Or if possible, check the plugins directory - that would catch if something has been manually added/deleted.

**Comment by Garywoo** [comment]
This has been a feature request on every iteration of every BeatSaber mod tool. Adding this feature would make this version undeniably the best for users!

**Comment by megalon** [comment]
Closed as of #23
