### ISSUE TITLE
OneClick download

### ISSUE THREAD

**Issue by Splamy** [beat-saber-modding-group/BeatSaberModInstaller#21]
The old modloader (from lolpants) had the feature to open modsaber (oneclick download) links to download a song from beatsaver. This new modmanager is missing such feature.

Would you accept such feature?
If yes I could properly implement it and create a pull request for it.
I have already tried a bit around and it doesnt seem to be too complicated.

Ui-wise maybe something like that:
![image](https://user-images.githubusercontent.com/6502527/55841031-e5e29b00-5b2d-11e9-9549-fa00f3478fad.png)

**Comment by megalon** [comment]
Yes, I would be interested in this feature, but haven't really looked into it.
Would it persist between updates of the Mod Manager? 
Since each version is a standalone `exe`, would you need to "register" it each time?

**Comment by Splamy** [comment]
The way in windows would be to create a registry entry `Computer\HKEY_CLASSES_ROOT\modsaber\shell\open\command` and set the path to the exe into it.
This means it would persist after each update, but when you move the exe somewhere else it would break.
My solution for this would be to check on startup in the config if the 'register onclick' was enabled and check if the path is correct, otherwise update it. This way fixing the link after moving the exe would just require the program to start once.

On linux, I don't have that much experience, but it should be similar but with a '.destop' file instead of a registry entry.

**Comment by megalon** [comment]
That sounds good to me.
I'll accept the PR if you can get it to work for Windows.

**Comment by Assistant** [comment]
I'd prefer if you used a different URI for it, though.

**Comment by Splamy** [comment]
@Assistant could you explain what you mean with that?
Do you mean the protocol `modsaber://`?
Using a different or even multiple protocols would be no problem implementing, however someone would have to get in contact with a maintainer of beatsaver.com to change it on the website.

**Comment by Assistant** [comment]
Yes, that's what I mean. I'm the current owner of beatsaver.com so that won't be an issue.

**Comment by Splamy** [comment]
Sure, make a suggestion, and I can change it in my pr

**Comment by Assistant** [comment]
BeatDrop will have a similar feature and will use `beatdrop://download/967-650`, so using that and allowing the user to pick would be the best, imo.

**Comment by Splamy** [comment]
Interesting, do you know if (or how) this scheme also applies to the avatar, platforms and sabers urls like `modsaber://avatar/https://modelsaber.com/files/avatar/1553498853/Gnoll.avatar`

**Comment by Assistant** [comment]
BeatDrop doesn't support ModelSaber one click installs yet, so we can come up with a standard and I can tell the programmer to use that.

**Comment by Splamy** [comment]
Some suggestions

Var A: 
+ Just modsaber as beatdrop protocol
```
beatdrop://avatar/https://modelsaber.com/files/avatar/1553498853/Gnoll.avatar
beatdrop://saber/https://modelsaber.com/files/saber/1553559541/Hestia%20Sword.saber
beatdrop://platform/https://modelsaber.com/files/platform/1553212170/Arch.plat
```

Var B:
+ short
+ somewhat more consistent with `beatdrop://download/967-650`
```
beatdrop://avatar/1553498853/Gnoll.avatar
beatdrop://saber/1553559541/Hestia%20Sword.saber
beatdrop://platform/1553212170/Arch.plat
```
(the part after the id could be omitted and inferred, but would need an additional request to the modelsaber api afaik)

Var C:
+ decentralized, allows other websites to provide such files
```
beatdrop://avatar?url=https://modelsaber.com/files/avatar/1553498853/Gnoll.avatar
beatdrop://saber?url=https://modelsaber.com/files/saber/1553559541/Hestia%20Sword.saber
beatdrop://platform?url=https://modelsaber.com/files/platform/1553212170/Arch.plat
```

Variant B seems the most reasonable to me.

**Comment by Assistant** [comment]
A and C are functionally the same, aren't they? It was designed that way with the full URL so that it would be decentralized. 

I like option B. Would registering multiple protocols be a hassle? I'll see what the BeatDrop dev has to say about making it be `modelsaber://`

**Comment by Splamy** [comment]
> A and C are functionally the same, aren't they?

Hm, haha yes, I guess I'm too tired to think properly anymore

I've also thought about adding another protocol for modelsabel, my thought was like `model_avatar://`, .. for each, but that seems like too much clutter. But I like the `modelsaber://` approach as it more or less ties the protocol to the website 'beatsaver:beatdrop' and 'modelsaber:modelsaber'

Btw, I rewrote the code in my pr a bit; It now supports the old modsaber protocol, the new beatdrop and is extensible for adding/removing protocols without much effort.

**Comment by Assistant** [comment]
I played with the idea to separate the BeatSaver protocol from BeatDrop, but I think that BeastSaber will also use it, so it doesn't make much sense to name it `beatsaver://`.

By the way, does your PR handle ModelSaber installations? I could change it to the new format so you can test it if you'd like.

**Comment by Splamy** [comment]
I currently added modsaber:// with song,avatar,platform,saber and beatdrop:// with songs only, as I didn't know yet which variant we would take.
You can swap it and I can check it tomorow; (it's really late here and I'm not at my pc anymore)

And I actually think `beatsaver://` could make sense. The protocol specifies what data it gives not which program shoud read it. It's kinda like `mailto:`, the website gives you a mail and you choose what email program you want to use. Same with songs and models

**Comment by Splamy** [comment]
Ok, I quickly updated the code. It now supports all `modsaber://` (until all links are changed), `beatdrop://` for songs and preliminary all model types too (treats them like modelsaber), and `modelsabel://` with all model types. For now I have implemented uri parsing as in variant B.

**Comment by Assistant** [comment]
Just went ahead and updated ModelSaber to use `modelsaber://` with variant B.
