### ISSUE TITLE
Feature Request: Sort by thumbs up in song list

### ISSUE THREAD

**Issue by tparnell90** [beat-saber-modding-group/BeatSaberModInstaller#24]
Sorting in any manner would be wonderful. In game sorting sucks, top downloaded isn't good as it still only shows those that were gotten at the top of hype. If there was top downloaded this month or something that might work. Ideally I think we should use the upvotes system more. I would love to see the top 100 most upvoted songs. Usually but not always they are good.

**Comment by Assistant** [comment]
Did you post this in the wrong repo? This is the Mod Manager, all it does is install mods, it doesn't do anything in game.
