### ISSUE TITLE
Problem with "Drink some water" Message

### ISSUE THREAD

**Issue by PyrexianYT** [beat-saber-modding-group/BeatSaberModInstaller#33]
When I've played a few games and the "Drink some water" message shows up, there's no way to close it (for me at least) and I have to close and re-open my game. Is there any way to fix this or get it to work? Sorry if there's already a way and I'm just and idiot! Thanks!

**Comment by bleutwo** [comment]
If you're talking about the [BeatSaberDrinkWater plugin](https://github.com/Shoko84/BeatSaberDrinkWater), you can better report that [here](https://github.com/Shoko84/BeatSaberDrinkWater/issues).
