### ISSUE TITLE
Cannot run Beat Saber after only installing required mods

### ISSUE THREAD

**Issue by Encline** [beat-saber-modding-group/BeatSaberModInstaller#34]
Hello,

Every time I try to run Beat Saber, the game won't start. Immediately the Unity Crash Handler appears, with the game running on a black screen in the background. The loading bar never moves past what is shown, and after a few seconds it crashes completely.

![image](https://user-images.githubusercontent.com/30320019/56084510-70125400-5df9-11e9-9d4e-f8489690e5b9.png)

I only have the Mod Manager and required mods downloaded. So, I would think that it is just the Mod Manager. I uninstalled and the base game worked fine, but when I reinstall the Mod Manager it crashes the same way.

Any ideas on why this is happening? Thanks all.

**Comment by megalon** [comment]
This is a pretty common issue we've been seeing a lot since the v0.13.2 update (and transition to BSIPA).

See this issue:
https://github.com/nike4613/BeatSaber-IPA-Reloaded/issues/6

Try this:
> 
> Clean Reinstall
> 1. Make sure to back up your CustomSongs folder and any of the other Custom folders before uninstalling
> 2. Uninstall Beat Saber
> 3. Delete your "Beat Saber" folder
> 4. Reinstall the game, then make sure to run it once without modding it, then close it
> 5. Mod the game using the latest Mod Manager https://github.com/beat-saber-modding-group/BeatSaberModInstaller/releases/latest

Also, to get faster help, visit #support on the Discord
https://discord.gg/beatsabermods

**Comment by Encline** [comment]
Thanks, that worked for me.
