### ISSUE TITLE
Won't Recognize Second HD

### ISSUE THREAD

**Issue by basnelso** [beat-saber-modding-group/BeatSaberModInstaller#36]
The mod manager wont let you search outside of your C drive for the beat saber installation, thus if you have beat saber installed on a second HD you can't use it to mod your game.

**Comment by Assistant** [comment]
AFAIK it uses the windows' file picker. It uses the older one, which is a bit trickier to navigate through, so make sure you looked in the right place.

**Comment by ItsNovaHere** [comment]
Other drives are under `This PC` near the top.
