### ISSUE TITLE
Error upon viewing selected mod info when no info is given from BeatMods

### ISSUE THREAD

**Issue by Awagi** [beat-saber-modding-group/BeatSaberModInstaller#40]
An exception happens especially when trying to view info of the newly updated SongBrowser mod (either right-clicking or the button).

![image](https://user-images.githubusercontent.com/4955434/56442999-f8f62780-62f2-11e9-814d-84389e732285.png)

```
System.InvalidOperationException: Impossible de démarrer le processus, car un nom de fichier n'a pas été indiqué.
   à System.Diagnostics.Process.Start()
   à System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   à BeatSaberModManager.FormMain.ButtonViewInfo2_Click(Object sender, EventArgs e)
   à System.Windows.Forms.Control.OnClick(EventArgs e)
   à System.Windows.Forms.Button.OnClick(EventArgs e)
   à System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   à System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   à System.Windows.Forms.Control.WndProc(Message& m)
   à System.Windows.Forms.ButtonBase.WndProc(Message& m)
   à System.Windows.Forms.Button.WndProc(Message& m)
   à System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

From BeatMods.com the "More Info" button isn't existent for the SongBrowser card.

The Mod Manager expected behavior should be to handle the lack of this "More Info", I guess, if mods with no info redirection are allowed at BeatMods.

**Comment by raftario** [comment]
I'll take care of that.

**Comment by megalon** [comment]
Yeah SongBrowser wasn't uploaded with a "More Info" link, so the Mod Manager is throwing an error saying it's trying to start a process for an empty string.

**Comment by megalon** [comment]
We've updated the post on BeatMods (thanks Kyle!) to include a link to the repo for SongBrowser, but the bug still stands.
