### ISSUE TITLE
Song loader plugin is shown as installable in latest version, but isn't updated.

### ISSUE THREAD

**Issue by CrayzCrinkle** [beat-saber-modding-group/BeatSaberModInstaller#49]
As per title, can you remove it from the list as it's not working with the current version?

**Comment by Assistant** [comment]
This program doesn't decide what plugins it lists, it takes them from BeatMods.

I also don't believe that's correct, Song Loader should be working, what is wrong with it?

**Comment by megalon** [comment]
If you are still having issues, see
https://bsmg.wiki/support

If you were able to determine it is an issue with SongLoader specifically, see
https://github.com/Kylemc1413/BeatSaberSongLoader
