### ISSUE TITLE
Downloaded songs extracted in wrong folder

### ISSUE THREAD

**Issue by srmo** [beat-saber-modding-group/BeatSaberModInstaller#50]
Hi, I'm new to the scene and probably reporting at the wrong place. But I don't know which plugin is responsible for the following behavior:

Version: 
* Latest Beatsaber/Oculus and latest BeatSaberModInstaller release

What's happening:
* I'm downloading songs from within the game (BeatSaver?)
* Songs do not appear in the  "Custom Songs" playlist

Observation:
Looking at the beatsaver/custom-songs folder, I see that songs aren't downloaded at the top level of this directory but get unzipped into numerical folders.
I.e. The song folder "TTFW" isn't present in `custom-songs/` but `custom-songs/31-59/` or something the like. That happens for all downloaded songs.

When I move the folders from those numerical folders into the custom-songs folder and restart beat saber, they are correctly displayed as available in the custom playlist. 

I don't see a way to configure the plugin.

Please point me in the right direction, and thanks for keeping this modding alive! :)

**Comment by Assistant** [comment]
This program simply installs plugins, bugs regarding those plugins should go on their respective places. I believe there's a button that takes you there in the installer when you select a plugin. 

>Looking at the beatsaver/custom-songs folder, I see that songs aren't downloaded at the top level of this directory but get unzipped into numerical folders.
That's how it's meant to work. Have you tried leaving them in those folders and restarting the game? 
I've heard that Song Browser has issues refreshing downloaded songs, so maybe try without Song Browser?

**Comment by megalon** [comment]
Within the mod manager, you can view mod info for each mod by either right clicking on a mod then selecting `View Info`.
Or select a mod in the list, and click on the `VIEW SELECTED MOD INFO` at the bottom.
In most cases this will take you to the GitHub page for that mod.

**Comment by srmo** [comment]
Thanks! Sorry for the late response.
