### ISSUE TITLE
Fatal error in GC - GetThreadContext failed

### ISSUE THREAD

**Issue by jharvey00** [beat-saber-modding-group/BeatSaberModInstaller#53]
![Capture](https://user-images.githubusercontent.com/50184282/57042333-5878ff00-6c32-11e9-984d-2ed718f267d2.PNG)
Downloaded mods and game won't even launch. Only getting this error. Did everything I can think of, reinstalling verifying files, redownloading everything under the sun. 
Game launches fine in Vanilla, and only crashes after installing mods.

I also tried installing the mods manually. All was fine until I ran the IPA "Beatsaber (Patch&Launch)
![1](https://user-images.githubusercontent.com/50184282/57042472-ba396900-6c32-11e9-8e63-2dd52bd20657.PNG)

**Comment by megalon** [comment]
This is an issue with BSIPA, not the Mod Installer.
See this link
https://github.com/beat-saber-modding-group/BeatSaber-IPA-Reloaded/issues/8
