### ISSUE TITLE
Custom songs not appearing in song list

### ISSUE THREAD

**Issue by DentalVan** [beat-saber-modding-group/BeatSaberModInstaller#57]
Every time i download a new song, it won't show up in the custom song list. The game needs me to restart it EVERY time i download a new song in order to play it. Even then, it doesn't seem to be guaranteed to show up in the list and if it does, it might not actually play the song i selected. I have tried to delete a song in order to redownload it to see if that would help, but the game didn't seem to recognise the deletion, so now i cannot find it in my list or download it. This version of the Beat Saber mod seems to be incredibly unreliable. I might uninstall it and wait for a future version to come out when it might not be so frustrating!
Not sure what other details I can give, but if anyone has any questions, I'd be more than happy to answer them.

**Comment by Kylemc1413** [comment]
That's not an issue relevant to the mod installer, if you're having issues with specific mods go to the support channel in the modding discord linked in the help section of the installer
