### ISSUE TITLE
ScoreSaber: Oculus version of DLL is downloaded instead of Steam version

### ISSUE THREAD

**Issue by n3tman** [beat-saber-modding-group/BeatSaberModInstaller#6]
Not sure if there are any built-in checks to download the right version, but I'm on Steam an I got the Oculus DLL (321,536 bytes) instead of Steam DLL (313,856 bytes).

This produces an error and scores don't work:

```
[ERROR @ 22:36:31 | IPA/Loader] Could not load ScoreSaber.dll! System.Reflection.ReflectionTypeLoadException: Exception of type 'System.Reflection.ReflectionTypeLoadException' was thrown.
[ERROR @ 22:36:31 | IPA/Loader]   at (wrapper managed-to-native) System.Reflection.Assembly.GetTypes(System.Reflection.Assembly,bool)
[ERROR @ 22:36:31 | IPA/Loader]   at System.Reflection.Assembly.GetTypes () [0x00000] in <d7ac571ca2d04b2f981d0d886fa067cf>:0
[ERROR @ 22:36:31 | IPA/Loader]   at IPA.Loader.PluginManager.LoadPluginsFromFile (System.String file) [0x00043] in <9def8fd80d414c4a888f7fa70ee68951>:0
```

Manual install of the right DLL fixes the problem. But I see people already report it, so I guess it's better to fix it.

**Comment by megalon** [comment]
I'll take a look at this, I think I might know what's causing it. Thanks

**Comment by megalon** [comment]
Apparently this is still happening.

**Comment by megalon** [comment]
Here is the relevant code section if anyone is interested in trying to figure out why this is still happening.

I'm wondering if sometimes the API doesn't return both files, so it defaults to assuming there is only one file, and thus installing the Steam version.

https://github.com/beat-saber-modding-group/BeatSaberModInstaller/blob/641c63a257a55f13d508de1f0e46d7ac6d180dae/BeatSaberModManager/Core/RemoteLogic.cs#L76-L108
