### ISSUE TITLE
Update to work with beatsaber 1.0.1

### ISSUE THREAD

**Issue by mike1000195** [beat-saber-modding-group/BeatSaberModInstaller#67]
updated beatsaber to 1.0.1 and mods stopped working, wondering if new version is being made.

**Comment by megalon** [comment]
Version 1.0.0 mods should work with v1.0.1 as well. Try running the installer again, or try using Mod Assistant if it doesn't work https://github.com/Assistant/ModAssistant

**Comment by mike1000195** [comment]
thank you! it updated the other day and didn't work, and i went to install and got hit with a big ass error message saying that it only supports 1.0.0. got it working now, but its not liking custom platforms too much lol
