### ISSUE TITLE
Does not copy plugins to Plugins folder the first time Install / Update is pressed

### ISSUE THREAD

**Issue by megalon** [beat-saber-modding-group/BeatSaberModInstaller#7]
Plugins do not get copied over to the `Beat Saber/Plugins` folder the first time it is pressed after launching the program. 
Installing / Updating again seems to fix it.

**Comment by Assistant** [comment]
Unless I'm mistaken I think you're looking at a BSIPA feature as a bug. BSIPA has a directory where it stores the pending changes to the game, which it applies when you open Beat Saber. Does the bug remain after opening the game?

**Comment by megalon** [comment]
You are right. 
I'm still getting used to BSIPA
